### ISSUE TITLE
Add Creative Commons attribution info to each tweet

### ISSUE THREAD

**Issue by jeancochrane** [jeancochrane/chanomemes#2]
This is a must-have prior to launch. Something like: 

"Thanks to `{{Flickr account}}` for the great CC-licensed image :) `{{link to CC license, per terms of attribution}}`"

We'll probably want to introduce a conditional block to check whether the license requires attribution or not, because this could get annoying if it's pasted on every reply.

**Comment by beamalsky** [comment]
OR 

📸 : {url}

**Comment by beamalsky** [comment]
OR 

CC-licensed images from: http://bit.ly/2nMljbv

in the account bio or pinned tweet.
