### ISSUE TITLE
Make a queue instead of replying automatically

### ISSUE THREAD

**Issue by jeancochrane** [jeancochrane/chanomemes#6]
We should have to review every meme before it goes out.

**Comment by kalilsn** [comment]
@jeancochrane I'll take this one! Here's my proposed architecture:

- Always running bot process receives tweets, parses them for meme text, and overlays it onto images saved in `images` directory
    - Saves memes as `queue/{tweet_id}.png`
    - Bot saves metadata as `queue/{tweet_id}.json` with the following fields:
        - tweet id
        - reply to tweet id
        - reply to user
        - original tweet text
        - meme text
        - timestamp
- Serve a simple moderation queue at chano4mayor.com/moderation, using something like [sinatra](http://www.sinatrarb.com/), [flask](https://bottlepy.org/docs/dev/), or maybe just straight php. Doesn't really matter, it just has to be easy and support authentication. Open to suggestions!
    - Page will require sign in
    - After authentication it should just show the oldest image in the queue, and a button to accept or reject the image
       - Should allow you to provide a reason for rejection
    - On click, send a post request
        - On accept post to `chano4mayor.com/moderation/approve/{tweet_id}`
        - On rejection post to `chano4mayor.com/moderation/reject/{tweet_id}`
    - After receiving an approval post, construct and send a tweet to the appropriate user
        - After confirming the tweet sent successfully, move image/metadata to `archive`
    - After receiving a rejection post, move image and metadata (with added reason) to `rejected`

**Comment by kalilsn** [comment]
This will definitely take some refactoring of the bot but hopefully not too much! I can see this either working as something where the server script (assuming it's bottle.py) imports a method for constructing/sending a tweet or simply making a standalone script to send a tweet that accepts a command line parameter to specify the necessary info.

**Comment by jeancochrane** [comment]
This looks like a great plan! I wonder if it's too ambitious to try to
launch with this on Saturday, though. What are some ways we could skip the
admin backend (or launch a simpler version while we tweak it)? I could see
it working fine if it just saves the image somewhere, and we keep an eye on
email notifications. Or we could see if Twitter exposes drafts to the API,
and try to save the tweets as drafts for review?

On Thu, Mar 30, 2017 at 6:51 PM Kalil Smith-Nuevelle <
notifications@github.com> wrote:

This will definitely take some refactoring of the bot but hopefully not too
much! I can see this either working as something where the server script
(assuming it's bottle.py) imports a method for constructing/sending a tweet
or simply making a standalone script to send a tweet that accepts a command
line parameter to specify the necessary info.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/jeancochrane/chanomemes/issues/6#issuecomment-290577092>,
or mute the thread

**Comment by kalilsn** [comment]
Oof yeah this is not feasible by Saturday – I was assuming this would mean putting off the bot for a bit. The drafts thing is a great idea though! If there's an api endpoint for adding a draft, I think that's definitely the best way forward.

**Comment by kalilsn** [comment]
there's no drafts endpoint 😒

**Comment by jeancochrane** [comment]
OK, talked about this with @beamalsky. We think the best way to move forward will be to use emails: attach the image to an email (Python [email module](https://docs.python.org/3/library/email-examples.html) seems to support this), along with the text of the tweet @ us and suggested reply text, and then email it to whoever is in charge of approving the tweets.

Sound good @kalilsn? If so, I'll move on this and hopefully have it implemented in the next hour or so.
